import type { Metadata } from 'next';
import { Inter, DM_Sans } from 'next/font/google';
import './globals.css';
import React from "react";

const dmSans = DM_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{children: React.ReactNode;}>) {
	return (
		<html lang="en" className={`${dmSans.className}`}>
		<body
			suppressHydrationWarning={true} // This prevents extensions from causing a server/client mismatch
			>
			{children}
			</body>
		</html>
	)
}

