import type { Metadata } from 'next';
import { Inter, DM_Sans } from 'next/font/google';
import './globals.css';
import React from "react";

const dmSans = DM_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
									   children,
								   }: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
            <body className={`${dmSans.className} m-3 bg-white`}>
                <h1 className="text-3xl font-bold">Reverse Semantle</h1>
                {children}
			</body>
		</html>
	);
}
